export { LandingPage } from "../pages/LandingPage/LandingPage";
export { ProductPage } from "../pages/ProductPage/ProductPage";
export { CartPage } from "../pages/CartPage/CartPage";
export { SignUp } from "../pages/SignUpPage/SignUp";
export { LoginPage } from "../pages/LoginPage/LoginPage";
export { WishlistPage } from "../pages/WishlistPage/WishlistPage";
export { UserProfile } from "../pages/UserProfile/UserProfile";
export { PageNotFound } from "../pages/PageNotFound/PageNotFound";
export {SingleProductPage} from '../pages/SingleProductPage/SingleProductPage';
export {AddressPage} from '../pages/AddressPage/AddressPage';
